export const DEMO_PROVIDERS = [
  {
    id: 'demo-1',
    name: 'Sofia Rodriguez',
    emoji: '💇‍♀️',
    location: { city: 'New York', lat: 40.7128, lng: -74.006 },
    bio: 'Award-winning hair stylist with 10+ years of experience. Specializing in balayage, color corrections, and bridal styling. Every client leaves feeling their absolute best.',
    categories: ['Hair', 'Bridal', 'Styling'],
    services: [
      { name: 'Haircut & Blowout', price: 85, category: 'Hair', durationMins: 60 },
      { name: 'Balayage', price: 250, category: 'Hair', durationMins: 180 },
      { name: 'Color Correction', price: 300, category: 'Hair', durationMins: 240 },
      { name: 'Bridal Package', price: 350, category: 'Bridal', durationMins: 240 },
    ],
    availability: { monday: { start: '09:00', end: '18:00' }, tuesday: { start: '09:00', end: '18:00' }, wednesday: { start: '09:00', end: '18:00' }, thursday: { start: '09:00', end: '20:00' }, friday: { start: '09:00', end: '18:00' }, saturday: { start: '10:00', end: '16:00' } },
    rating: 4.9,
    reviewCount: 142,
  },
  {
    id: 'demo-2',
    name: 'Marcus Johnson',
    emoji: '✂️',
    location: { city: 'New York', lat: 40.7282, lng: -73.7949 },
    bio: 'Master barber with 8 years in the industry. Clean fades, beard shaping, and classic cuts are my specialty. Walk-ins welcome.',
    categories: ['Barber', 'Beard'],
    services: [
      { name: 'Classic Haircut', price: 40, category: 'Barber', durationMins: 45 },
      { name: 'Skin Fade', price: 50, category: 'Barber', durationMins: 50 },
      { name: 'Beard Shaping', price: 30, category: 'Beard', durationMins: 30 },
      { name: 'Haircut + Beard', price: 70, category: 'Barber', durationMins: 75 },
    ],
    availability: { monday: { start: '08:00', end: '18:00' }, tuesday: { start: '08:00', end: '18:00' }, wednesday: { start: '08:00', end: '18:00' }, thursday: { start: '08:00', end: '18:00' }, friday: { start: '08:00', end: '18:00' }, saturday: { start: '09:00', end: '17:00' } },
    rating: 4.8,
    reviewCount: 98,
  },
  {
    id: 'demo-3',
    name: 'Priya Patel',
    emoji: '💅',
    location: { city: 'New York', lat: 40.7580, lng: -73.9855 },
    bio: 'Nail artist and esthetics expert. From gel manis to intricate nail art, I create stunning looks that last. Skin care treatments also available.',
    categories: ['Nails', 'Nail Art', 'Esthetics'],
    services: [
      { name: 'Gel Manicure', price: 55, category: 'Nails', durationMins: 60 },
      { name: 'Acrylic Full Set', price: 75, category: 'Nails', durationMins: 90 },
      { name: 'Nail Art Design', price: 90, category: 'Nail Art', durationMins: 90 },
      { name: 'Facial', price: 100, category: 'Esthetics', durationMins: 60 },
    ],
    availability: { tuesday: { start: '10:00', end: '19:00' }, wednesday: { start: '10:00', end: '19:00' }, thursday: { start: '10:00', end: '19:00' }, friday: { start: '10:00', end: '19:00' }, saturday: { start: '09:00', end: '18:00' }, sunday: { start: '11:00', end: '17:00' } },
    rating: 5.0,
    reviewCount: 76,
  },
  {
    id: 'demo-4',
    name: 'Isabella Chen',
    emoji: '💄',
    location: { city: 'New York', lat: 40.7614, lng: -73.9776 },
    bio: 'Professional makeup artist for editorial, events, and everyday glam. I believe in enhancing your natural beauty with premium products.',
    categories: ['Makeup', 'Bridal'],
    services: [
      { name: 'Everyday Makeup', price: 80, category: 'Makeup', durationMins: 60 },
      { name: 'Event Glam', price: 120, category: 'Makeup', durationMins: 75 },
      { name: 'Bridal Makeup', price: 200, category: 'Bridal', durationMins: 120 },
      { name: 'Makeup Lesson', price: 150, category: 'Makeup', durationMins: 90 },
    ],
    availability: { monday: { start: '09:00', end: '18:00' }, wednesday: { start: '09:00', end: '18:00' }, friday: { start: '09:00', end: '20:00' }, saturday: { start: '08:00', end: '18:00' }, sunday: { start: '08:00', end: '16:00' } },
    rating: 4.7,
    reviewCount: 211,
  },
  {
    id: 'demo-5',
    name: 'Amir Hassan',
    emoji: '🧖‍♂️',
    location: { city: 'New York', lat: 40.6892, lng: -74.0445 },
    bio: 'Licensed esthetician specializing in waxing, skin treatments, and men\'s grooming. Painless waxing techniques using premium products.',
    categories: ['Waxing', 'Esthetics'],
    services: [
      { name: 'Full Leg Wax', price: 70, category: 'Waxing', durationMins: 60 },
      { name: 'Brazilian Wax', price: 65, category: 'Waxing', durationMins: 45 },
      { name: 'Back Wax', price: 55, category: 'Waxing', durationMins: 45 },
      { name: 'Skin Treatment', price: 90, category: 'Esthetics', durationMins: 60 },
    ],
    availability: { monday: { start: '10:00', end: '19:00' }, tuesday: { start: '10:00', end: '19:00' }, thursday: { start: '10:00', end: '19:00' }, friday: { start: '10:00', end: '19:00' }, saturday: { start: '10:00', end: '18:00' } },
    rating: 4.6,
    reviewCount: 54,
  },
  {
    id: 'demo-6',
    name: 'Zara Williams',
    emoji: '👰',
    location: { city: 'New York', lat: 40.7484, lng: -73.9967 },
    bio: 'Full-service bridal beauty specialist. Hair, makeup, nails — I handle it all to make your special day absolutely perfect.',
    categories: ['Bridal', 'Hair', 'Makeup'],
    services: [
      { name: 'Full Bridal Package', price: 650, category: 'Bridal', durationMins: 360 },
      { name: 'Bridal Trial', price: 200, category: 'Bridal', durationMins: 120 },
      { name: 'Bridesmaid Package', price: 180, category: 'Bridal', durationMins: 120 },
      { name: 'Bridal Hair Only', price: 250, category: 'Hair', durationMins: 150 },
    ],
    availability: { tuesday: { start: '09:00', end: '18:00' }, wednesday: { start: '09:00', end: '18:00' }, thursday: { start: '09:00', end: '18:00' }, friday: { start: '09:00', end: '20:00' }, saturday: { start: '07:00', end: '20:00' }, sunday: { start: '07:00', end: '18:00' } },
    rating: 4.9,
    reviewCount: 33,
  },
];

export const CATEGORIES = ['All', 'Hair', 'Nails', 'Makeup', 'Barber', 'Bridal', 'Waxing', 'Esthetics'];

export const TIME_SLOTS = [
  '9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM',
  '11:00 AM', '11:30 AM', '12:00 PM', '1:00 PM',
  '1:30 PM', '2:00 PM', '2:30 PM', '3:00 PM',
  '3:30 PM', '4:00 PM', '4:30 PM', '5:00 PM',
];
