export interface QuasarService {
  id: string;
  name: string;
  price: number;
  priceLabel?: string;
  durationMins: number;
  gender: 'Women' | 'Men' | 'Both';
  note?: string;
}

export interface QuasarCategory {
  id: string;
  name: string;
  icon: string;
  imageUrl: string | number;
  services: QuasarService[];
}

export interface StaffMember {
  id: string;
  name: string;
  role: string;
  emoji: string;
  specialties: string[];
  experience: string;
  available: boolean;
  schedule: {
    [day: string]: { start: string; end: string } | null;
  };
}

export const QUASAR_CATEGORIES: QuasarCategory[] = [
  {
    id: 'hair-care',
    name: 'Hair Care',
    icon: '💇‍♀️',
    imageUrl: require('../assets/services/hair-care.png'),
    services: [
      { id: 'hc-1', name: 'Wash & Natural Dry', price: 499, durationMins: 30, gender: 'Women' },
      { id: 'hc-2', name: 'Wash & Blow Dry', price: 649, durationMins: 45, gender: 'Women' },
      { id: 'hc-3', name: 'Hair Styling (Without Wash)', price: 249, durationMins: 20, gender: 'Men' },
      { id: 'hc-4', name: 'Hair Styling (With Wash)', price: 349, durationMins: 30, gender: 'Men' },
      { id: 'hc-5', name: 'Hair Wash & Blow Dry (Premium)', price: 549, durationMins: 45, gender: 'Men', note: 'Cotril/Fiber Clinix/Blue Shampoo' },
      { id: 'hc-6', name: 'Hair Wash & Blow Dry (Nashi)', price: 999, durationMins: 50, gender: 'Women' },
      { id: 'hc-7', name: 'Hair Wash & Blow Dry (Nashi)', price: 599, durationMins: 45, gender: 'Men' },
      { id: 'hc-8', name: 'Men Hair Cut', price: 599, durationMins: 30, gender: 'Men' },
      { id: 'hc-9', name: 'Beard Cut / Shave', price: 399, durationMins: 20, gender: 'Men' },
      { id: 'hc-10', name: 'Beard Color', price: 999, durationMins: 30, gender: 'Men' },
      { id: 'hc-11', name: 'Bigen Beard Color', price: 1199, durationMins: 40, gender: 'Men' },
      { id: 'hc-12', name: 'Moustache', price: 499, durationMins: 20, gender: 'Men' },
      { id: 'hc-13', name: 'Female Hair Cut', price: 999, durationMins: 45, gender: 'Women', note: 'Onwards' },
      { id: 'hc-14', name: 'Female Hair Trim', price: 849, durationMins: 30, gender: 'Women' },
      { id: 'hc-15', name: 'Creative Hair Cut (Sr. Stylist)', price: 1499, durationMins: 60, gender: 'Women', note: 'Onwards' },
      { id: 'hc-16', name: 'Boy Hair Cut (Below 5 Years)', price: 449, durationMins: 20, gender: 'Men' },
      { id: 'hc-17', name: 'Girl Hair Cut (Below 5 Years)', price: 599, durationMins: 20, gender: 'Women' },
      { id: 'hc-18', name: 'Curls Without Wash', price: 999, durationMins: 40, gender: 'Women' },
      { id: 'hc-19', name: 'Curls With Wash', price: 1199, durationMins: 50, gender: 'Women' },
      { id: 'hc-20', name: 'Curls With Nashi Wash', price: 1299, durationMins: 55, gender: 'Women' },
      { id: 'hc-21', name: 'Curls With Fiber Clinix Wash', price: 1499, durationMins: 60, gender: 'Women' },
      { id: 'hc-22', name: 'Maggie Curls / Flat Iron With Wash', price: 1599, durationMins: 75, gender: 'Women', note: 'Onwards' },
      { id: 'hc-23', name: 'Root Touchup (With Ammonia)', price: 1399, durationMins: 60, gender: 'Both' },
      { id: 'hc-24', name: 'Root Touchup (Without Ammonia)', price: 1599, durationMins: 60, gender: 'Both' },
    ],
  },
  {
    id: 'transformation',
    name: 'Transformation',
    icon: '🎨',
    imageUrl: require('../assets/services/transformation.png'),
    services: [
      { id: 'tr-1', name: 'Base Shade Global Color', price: 4499, durationMins: 120, gender: 'Women' },
      { id: 'tr-2', name: 'Fashion Global Color', price: 5999, durationMins: 120, gender: 'Women', note: 'Onwards' },
      { id: 'tr-3', name: 'Fashion Global Color', price: 2499, durationMins: 90, gender: 'Men', note: 'Onwards' },
      { id: 'tr-4', name: 'Highlights', price: 5999, durationMins: 150, gender: 'Women', note: 'Onwards' },
      { id: 'tr-5', name: 'Highlights', price: 3499, durationMins: 120, gender: 'Men', note: 'Onwards' },
      { id: 'tr-6', name: 'Baby Highlights (Babylights)', price: 6999, durationMins: 180, gender: 'Women', note: 'Onwards' },
      { id: 'tr-7', name: 'Low Highlights', price: 7999, durationMins: 180, gender: 'Women', note: 'Onwards' },
      { id: 'tr-8', name: 'Balayage', price: 6999, durationMins: 180, gender: 'Women', note: 'Onwards' },
    ],
  },
  {
    id: 'eyebrows',
    name: 'Eyebrow Studio',
    icon: '✨',
    imageUrl: require('../assets/services/eyebrow-studio.png'),
    services: [
      { id: 'eb-1', name: 'First Correction', price: 1200, durationMins: 60, gender: 'Both', note: 'By Sahil Khan' },
      { id: 'eb-2', name: 'Regular Eyebrows', price: 600, durationMins: 30, gender: 'Both', note: 'By Sahil Khan' },
      { id: 'eb-3', name: 'Powdering & Shading', price: 10000, durationMins: 120, gender: 'Both', note: 'Onwards' },
      { id: 'eb-4', name: 'Micro Blading', price: 15000, durationMins: 180, gender: 'Both', note: 'Onwards' },
    ],
  },
  {
    id: 'threading',
    name: 'Threading',
    icon: '🧵',
    imageUrl: require('../assets/services/threading.png'),
    services: [
      { id: 'th-1', name: 'Eyebrows', price: 100, durationMins: 10, gender: 'Women' },
      { id: 'th-2', name: 'Upper Lips', price: 100, durationMins: 10, gender: 'Women' },
      { id: 'th-3', name: 'Lower Lips', price: 100, durationMins: 10, gender: 'Women' },
      { id: 'th-4', name: 'Forehead', price: 150, durationMins: 10, gender: 'Women' },
      { id: 'th-5', name: 'Chin', price: 150, durationMins: 10, gender: 'Women' },
      { id: 'th-6', name: 'Side Locks', price: 150, durationMins: 10, gender: 'Women' },
      { id: 'th-7', name: 'Full Face', price: 599, durationMins: 30, gender: 'Women' },
    ],
  },
  {
    id: 'bleach',
    name: 'Bleach / D-Tan',
    icon: '🌟',
    imageUrl: require('../assets/services/bleach-dtan.png'),
    services: [
      { id: 'bl-1', name: 'Face Bleach / D-Tan', price: 849, durationMins: 30, gender: 'Both' },
      { id: 'bl-2', name: 'Face & Neck Bleach / D-Tan', price: 1199, durationMins: 40, gender: 'Both' },
      { id: 'bl-3', name: 'Full Arms Bleach / D-Tan', price: 749, durationMins: 30, gender: 'Both' },
      { id: 'bl-4', name: 'Full Legs Bleach / D-Tan', price: 899, durationMins: 40, gender: 'Both' },
      { id: 'bl-5', name: 'Half Back / Front Bleach / D-Tan', price: 999, durationMins: 40, gender: 'Both' },
      { id: 'bl-6', name: 'Full Back / Front Bleach / D-Tan', price: 1499, durationMins: 60, gender: 'Both' },
      { id: 'bl-7', name: 'Full Body Bleach / D-Tan', price: 1999, durationMins: 90, gender: 'Both' },
    ],
  },
  {
    id: 'cleanups',
    name: 'Cleanups',
    icon: '🧖',
    imageUrl: require('../assets/services/cleanups.png'),
    services: [
      { id: 'cl-1', name: 'Kanpeki Clean Up', price: 2499, durationMins: 45, gender: 'Both' },
      { id: 'cl-2', name: 'Derma Clean Up', price: 3499, durationMins: 60, gender: 'Both' },
      { id: 'cl-3', name: 'Deep Cleaning With Algae Mask (Thalgo)', price: 4999, durationMins: 75, gender: 'Both' },
      { id: 'cl-4', name: 'Power Mask (Add On)', price: 499, durationMins: 15, gender: 'Both' },
    ],
  },
  {
    id: 'facials',
    name: 'Facials',
    icon: '💆‍♀️',
    imageUrl: require('../assets/services/facials.png'),
    services: [
      { id: 'fa-1', name: 'Kanpeki Hydra Pro', price: 3499, durationMins: 60, gender: 'Both' },
      { id: 'fa-2', name: 'Red Wine Facial', price: 3999, durationMins: 60, gender: 'Both' },
      { id: 'fa-3', name: 'Derma Brightening (Without Machine)', price: 5499, durationMins: 75, gender: 'Both' },
      { id: 'fa-4', name: 'Derma Brightening (With Machine)', price: 7499, durationMins: 90, gender: 'Both' },
      { id: 'fa-5', name: 'Derma Hydration', price: 5999, durationMins: 75, gender: 'Both' },
      { id: 'fa-6', name: 'Derma Pro Glow With Bleach', price: 6999, durationMins: 90, gender: 'Both' },
      { id: 'fa-7', name: 'Derma Treatment', price: 8499, durationMins: 90, gender: 'Both' },
      { id: 'fa-8', name: 'Derma Eye Treatment', price: 2999, durationMins: 45, gender: 'Both' },
      { id: 'fa-9', name: 'Under Arms Facial', price: 1499, durationMins: 30, gender: 'Both' },
      { id: 'fa-10', name: 'Bikini Facial Without Wax', price: 2499, durationMins: 45, gender: 'Women' },
      { id: 'fa-11', name: 'Bikini Facial With Wax', price: 4999, durationMins: 60, gender: 'Women' },
    ],
  },
  {
    id: 'nails',
    name: 'Nail Studio',
    icon: '💅',
    imageUrl: require('../assets/services/nail-studio.png'),
    services: [
      { id: 'na-1', name: 'Nail Cut / Filing', price: 189, durationMins: 15, gender: 'Women' },
      { id: 'na-2', name: 'Regular Nail Paint', price: 199, durationMins: 20, gender: 'Women' },
      { id: 'na-3', name: 'Nail Paint Removal (Regular)', price: 99, durationMins: 15, gender: 'Women' },
      { id: 'na-4', name: 'Power / Gel Polish', price: 999, durationMins: 45, gender: 'Women' },
      { id: 'na-5', name: 'Power Polish Removal', price: 499, durationMins: 20, gender: 'Women' },
      { id: 'na-6', name: 'French / Cat Eye With Extension', price: 999, durationMins: 60, gender: 'Women' },
      { id: 'na-7', name: 'French / Cat Eye Without Extension', price: 1499, durationMins: 75, gender: 'Women' },
      { id: 'na-8', name: 'Fake Nail Extensions (Single Color)', price: 1499, durationMins: 75, gender: 'Women' },
      { id: 'na-9', name: 'Gel Extensions', price: 2499, durationMins: 90, gender: 'Women' },
      { id: 'na-10', name: 'Gel Extension Refiling', price: 1499, durationMins: 60, gender: 'Women' },
      { id: 'na-11', name: 'Gel Extension Removal', price: 799, durationMins: 30, gender: 'Women' },
      { id: 'na-12', name: 'Acrylic Extensions', price: 2999, durationMins: 90, gender: 'Women' },
      { id: 'na-13', name: 'Acrylic Extension Refiling', price: 1999, durationMins: 75, gender: 'Women' },
      { id: 'na-14', name: 'Acrylic Extension Removal', price: 999, durationMins: 30, gender: 'Women' },
      { id: 'na-15', name: 'Brush Nail Art', price: 149, durationMins: 15, gender: 'Women', note: 'Per finger' },
      { id: 'na-16', name: 'Nail Art', price: 100, durationMins: 10, gender: 'Women', note: 'Per finger' },
      { id: 'na-17', name: 'Nail Overlay Gel', price: 1199, durationMins: 60, gender: 'Women' },
      { id: 'na-18', name: 'Nail Overlay Acrylic', price: 1499, durationMins: 60, gender: 'Women' },
    ],
  },
  {
    id: 'waxing',
    name: 'Waxing',
    icon: '🌸',
    imageUrl: require('../assets/services/waxing.png'),
    services: [
      { id: 'wx-1', name: 'Eyebrows — Rica', price: 149, durationMins: 10, gender: 'Women' },
      { id: 'wx-2', name: 'Eyebrows — Peel Off', price: 299, durationMins: 10, gender: 'Women' },
      { id: 'wx-3', name: 'Upper Lip — Rica', price: 149, durationMins: 10, gender: 'Women' },
      { id: 'wx-4', name: 'Full Face — Rica', price: 899, durationMins: 30, gender: 'Women' },
      { id: 'wx-5', name: 'Half Arms — Honey', price: 399, durationMins: 20, gender: 'Women' },
      { id: 'wx-6', name: 'Half Arms — Rica', price: 599, durationMins: 20, gender: 'Women' },
      { id: 'wx-7', name: 'Full Arms — Honey', price: 599, durationMins: 30, gender: 'Women' },
      { id: 'wx-8', name: 'Full Arms — Rica', price: 799, durationMins: 30, gender: 'Women' },
      { id: 'wx-9', name: 'Half Legs — Honey', price: 499, durationMins: 25, gender: 'Women' },
      { id: 'wx-10', name: 'Full Legs — Honey', price: 699, durationMins: 40, gender: 'Women' },
      { id: 'wx-11', name: 'Full Legs — Rica', price: 899, durationMins: 40, gender: 'Women' },
      { id: 'wx-12', name: 'Underarms — Honey', price: 249, durationMins: 15, gender: 'Women' },
      { id: 'wx-13', name: 'Underarms — Rica', price: 349, durationMins: 15, gender: 'Women' },
      { id: 'wx-14', name: 'Full Body — Honey', price: 3999, durationMins: 90, gender: 'Women' },
      { id: 'wx-15', name: 'Full Body — Rica', price: 5999, durationMins: 90, gender: 'Women' },
      { id: 'wx-16', name: 'Bikini — Rica', price: 2499, durationMins: 30, gender: 'Women' },
      { id: 'wx-17', name: 'Half Arms (Men) — Honey', price: 499, durationMins: 25, gender: 'Men' },
      { id: 'wx-18', name: 'Full Arms (Men) — Honey', price: 799, durationMins: 35, gender: 'Men' },
    ],
  },
  {
    id: 'mani-pedi',
    name: 'Manicure & Pedicure',
    icon: '🤲',
    imageUrl: require('../assets/services/manicure-pedicure.png'),
    services: [
      { id: 'mp-1', name: 'Manicure — Lemon / Blueberry', price: 1000, durationMins: 40, gender: 'Women' },
      { id: 'mp-2', name: 'Pedicure — Lemon / Blueberry', price: 1000, durationMins: 40, gender: 'Women' },
      { id: 'mp-3', name: 'Manicure — AVI', price: 1400, durationMins: 40, gender: 'Women' },
      { id: 'mp-4', name: 'Pedicure — AVI', price: 1400, durationMins: 40, gender: 'Women' },
      { id: 'mp-5', name: 'Manicure — Mini Algae Fondue', price: 1800, durationMins: 50, gender: 'Women', note: 'With Steam' },
      { id: 'mp-6', name: 'Pedicure — Mini Algae Fondue', price: 1800, durationMins: 50, gender: 'Women', note: 'With Steam' },
      { id: 'mp-7', name: 'Manicure — Ice Cream Donut', price: 2000, durationMins: 60, gender: 'Women' },
      { id: 'mp-8', name: 'Pedicure — Ice Cream Donut', price: 2000, durationMins: 60, gender: 'Women' },
      { id: 'mp-9', name: 'Manicure — Algae / Candle / Potli', price: 2500, durationMins: 75, gender: 'Women' },
      { id: 'mp-10', name: 'Pedicure — Algae / Candle / Potli', price: 2500, durationMins: 75, gender: 'Women' },
      { id: 'mp-11', name: 'Quasar Signature Wine Manicure', price: 3000, durationMins: 90, gender: 'Women' },
      { id: 'mp-12', name: 'Quasar Signature Wine Pedicure', price: 3000, durationMins: 90, gender: 'Women' },
      { id: 'mp-13', name: 'Extra Massage 15 Min (Add On)', price: 499, durationMins: 15, gender: 'Both' },
      { id: 'mp-14', name: 'Extra Massage 30 Min (Add On)', price: 849, durationMins: 30, gender: 'Both' },
    ],
  },
  {
    id: 'massages',
    name: 'Massages',
    icon: '💆',
    imageUrl: require('../assets/services/massages.png'),
    services: [
      { id: 'ms-1', name: 'Head Massage With Natural Dry (30 Min)', price: 1000, durationMins: 30, gender: 'Both' },
      { id: 'ms-2', name: 'Head Massage With Natural Dry (45 Min)', price: 1200, durationMins: 45, gender: 'Both' },
      { id: 'ms-3', name: 'Head & Shoulder Massage (30 Min)', price: 1200, durationMins: 30, gender: 'Both' },
      { id: 'ms-4', name: 'Head & Shoulder Massage (45 Min)', price: 1400, durationMins: 45, gender: 'Both' },
      { id: 'ms-5', name: 'Head Massage With Blow Dry (30 Min)', price: 1200, durationMins: 30, gender: 'Both' },
      { id: 'ms-6', name: 'Head Massage With Blow Dry (45 Min)', price: 1400, durationMins: 45, gender: 'Both' },
      { id: 'ms-7', name: 'Dry Foot Massage (30 Min)', price: 850, durationMins: 30, gender: 'Both' },
      { id: 'ms-8', name: 'Dry Foot Massage (45 Min)', price: 1000, durationMins: 45, gender: 'Both' },
      { id: 'ms-9', name: 'Foot Massage With Cleansing (30 Min)', price: 1000, durationMins: 30, gender: 'Both' },
      { id: 'ms-10', name: 'Foot Massage With Cleansing (45 Min)', price: 1200, durationMins: 45, gender: 'Both' },
    ],
  },
  {
    id: 'body',
    name: 'Body Treatments',
    icon: '🛁',
    imageUrl: require('../assets/services/body-treatments.png'),
    services: [
      { id: 'bd-1', name: 'Swedish Therapy (60 Min)', price: 2500, durationMins: 60, gender: 'Both' },
      { id: 'bd-2', name: 'Swedish Therapy (90 Min)', price: 3500, durationMins: 90, gender: 'Both' },
      { id: 'bd-3', name: 'Deep Tissue Therapy (60 Min)', price: 3000, durationMins: 60, gender: 'Both' },
      { id: 'bd-4', name: 'Deep Tissue Therapy (90 Min)', price: 4500, durationMins: 90, gender: 'Both' },
      { id: 'bd-5', name: 'Candle Therapy (60 Min)', price: 3000, durationMins: 60, gender: 'Both' },
      { id: 'bd-6', name: 'Shell Therapy (60 Min)', price: 3500, durationMins: 60, gender: 'Both' },
      { id: 'bd-7', name: 'Shell Therapy (90 Min)', price: 5000, durationMins: 90, gender: 'Both' },
      { id: 'bd-8', name: 'Quasar Signature Therapy — Four Hand (60 Min)', price: 4500, durationMins: 60, gender: 'Both' },
      { id: 'bd-9', name: 'Quasar Signature Therapy — Four Hand (90 Min)', price: 6000, durationMins: 90, gender: 'Both' },
      { id: 'bd-10', name: 'Jacuzzi Bubble Bath (30 Min)', price: 2000, durationMins: 30, gender: 'Both' },
      { id: 'bd-11', name: 'Bomb Therapy With Bath Fizzer (30 Min)', price: 2500, durationMins: 30, gender: 'Both' },
      { id: 'bd-12', name: 'Moroccan Bath (Scrub + Massage + Pack + Jacuzzi)', price: 4999, durationMins: 90, gender: 'Both' },
      { id: 'bd-13', name: 'Body Scrubbing (30 Min)', price: 2000, durationMins: 30, gender: 'Both' },
      { id: 'bd-14', name: 'Black Pearl Detox (45 Min)', price: 3500, durationMins: 45, gender: 'Both', note: 'Flushes toxins & excess fluid' },
      { id: 'bd-15', name: 'Walnut / Manuka Honey Body Scrub (45 Min)', price: 4000, durationMins: 45, gender: 'Both', note: 'For brightening' },
      { id: 'bd-16', name: 'Coffee Scrub (45 Min)', price: 4500, durationMins: 45, gender: 'Both', note: 'Fat loss & brightening' },
    ],
  },
  {
    id: 'makeup',
    name: 'Make-Up',
    icon: '💄',
    imageUrl: require('../assets/services/makeup.png'),
    services: [
      { id: 'mu-1', name: 'Eye Make-Up (Party)', price: 1999, durationMins: 45, gender: 'Women' },
      { id: 'mu-2', name: 'Basic Make-Up (Party)', price: 3499, durationMins: 60, gender: 'Women' },
      { id: 'mu-3', name: 'HD Make-Up (Party)', price: 4499, durationMins: 75, gender: 'Women' },
      { id: 'mu-4', name: 'Glass Make-Up (Party)', price: 6499, durationMins: 90, gender: 'Women', note: 'Incl. Eyelashes' },
      { id: 'mu-5', name: 'Celebrity Party Make-Up', price: 8499, durationMins: 120, gender: 'Women', note: 'Incl. Eyelashes' },
      { id: 'mu-6', name: 'Engagement Make-Up', price: 9999, durationMins: 120, gender: 'Women' },
      { id: 'mu-7', name: 'Engagement HD Make-Up', price: 12999, durationMins: 150, gender: 'Women' },
      { id: 'mu-8', name: 'Engagement Glass Celebrity Make-Up', price: 14999, durationMins: 180, gender: 'Women' },
      { id: 'mu-12', name: 'Hair Do (Open Hair)', price: 1199, durationMins: 45, gender: 'Women' },
      { id: 'mu-13', name: 'Hair Do (With Bun)', price: 1499, durationMins: 60, gender: 'Women' },
      { id: 'mu-14', name: 'Hair Extension Application', price: 299, durationMins: 20, gender: 'Women' },
    ],
  },
  {
    id: 'jacuzzi',
    name: 'Jacuzzi & Spa',
    icon: '🛁',
    imageUrl: require('../assets/services/jacuzzi-spa.png'),
    services: [
      { id: 'jz-1', name: 'Jacuzzi Bubble Bath (30 Min)', price: 2000, durationMins: 30, gender: 'Both' },
      { id: 'jz-2', name: 'Bomb Therapy With Bath Fizzer (30 Min)', price: 2500, durationMins: 30, gender: 'Both' },
      { id: 'jz-3', name: 'Moroccan Bath (Scrub + Massage + Pack + Jacuzzi)', price: 4999, durationMins: 90, gender: 'Both' },
      { id: 'jz-4', name: 'Body Scrubbing (30 Min)', price: 2000, durationMins: 30, gender: 'Both' },
      { id: 'jz-5', name: 'Black Pearl Detox (45 Min)', price: 3500, durationMins: 45, gender: 'Both', note: 'Flushes toxins & excess fluid' },
      { id: 'jz-6', name: 'Walnut / Manuka Honey Body Scrub (45 Min)', price: 4000, durationMins: 45, gender: 'Both', note: 'For brightening' },
      { id: 'jz-7', name: 'Coffee Scrub (45 Min)', price: 4500, durationMins: 45, gender: 'Both', note: 'Fat loss & brightening' },
    ],
  },
  {
    id: 'bridal',
    name: 'Bridal',
    icon: '👰',
    imageUrl: require('../assets/services/bridal.png'),
    services: [
      { id: 'br-1', name: 'Engagement Make-Up', price: 9999, durationMins: 120, gender: 'Women' },
      { id: 'br-2', name: 'Engagement HD Make-Up', price: 12999, durationMins: 150, gender: 'Women' },
      { id: 'br-3', name: 'Engagement Glass Celebrity Make-Up', price: 14999, durationMins: 180, gender: 'Women' },
      { id: 'br-4', name: 'Bridal HD Make-Up', price: 14999, durationMins: 180, gender: 'Women' },
      { id: 'br-5', name: 'Bridal Glass Make-Up', price: 24999, durationMins: 240, gender: 'Women' },
      { id: 'br-6', name: 'Bridal Celebrity Make-Up', price: 34999, durationMins: 300, gender: 'Women' },
      { id: 'br-7', name: 'Bridal Hair Do (Open Hair)', price: 1199, durationMins: 45, gender: 'Women' },
      { id: 'br-8', name: 'Bridal Hair Do (With Bun)', price: 1499, durationMins: 60, gender: 'Women' },
    ],
  },
];

export const QUASAR_STAFF: StaffMember[] = [
  {
    id: 'staff-1',
    name: 'Priya Sharma',
    role: 'Senior Hair Stylist',
    emoji: '💇‍♀️',
    specialties: ['Hair Care', 'Transformation', 'Bridal'],
    experience: '8 years',
    available: true,
    schedule: {
      monday: { start: '10:00', end: '20:00' },
      tuesday: { start: '10:00', end: '20:00' },
      wednesday: null,
      thursday: { start: '10:00', end: '20:00' },
      friday: { start: '10:00', end: '20:00' },
      saturday: { start: '09:00', end: '21:00' },
      sunday: { start: '09:00', end: '18:00' },
    },
  },
  {
    id: 'staff-2',
    name: 'Rahul Verma',
    role: 'Expert Barber',
    emoji: '✂️',
    specialties: ['Hair Care', 'Beard'],
    experience: '6 years',
    available: true,
    schedule: {
      monday: { start: '09:00', end: '19:00' },
      tuesday: { start: '09:00', end: '19:00' },
      wednesday: { start: '09:00', end: '19:00' },
      thursday: null,
      friday: { start: '09:00', end: '19:00' },
      saturday: { start: '09:00', end: '21:00' },
      sunday: { start: '10:00', end: '18:00' },
    },
  },
  {
    id: 'staff-3',
    name: 'Sahil Khan',
    role: 'Eyebrow Artist',
    emoji: '✨',
    specialties: ['Eyebrow Studio', 'Threading', 'Waxing'],
    experience: '10 years',
    available: true,
    schedule: {
      monday: { start: '11:00', end: '20:00' },
      tuesday: { start: '11:00', end: '20:00' },
      wednesday: { start: '11:00', end: '20:00' },
      thursday: { start: '11:00', end: '20:00' },
      friday: null,
      saturday: { start: '10:00', end: '21:00' },
      sunday: null,
    },
  },
  {
    id: 'staff-4',
    name: 'Neha Kapoor',
    role: 'Skin & Facial Expert',
    emoji: '💆‍♀️',
    specialties: ['Facials', 'Cleanups', 'Bleach / D-Tan'],
    experience: '7 years',
    available: true,
    schedule: {
      monday: { start: '10:00', end: '19:00' },
      tuesday: null,
      wednesday: { start: '10:00', end: '19:00' },
      thursday: { start: '10:00', end: '19:00' },
      friday: { start: '10:00', end: '19:00' },
      saturday: { start: '09:00', end: '20:00' },
      sunday: { start: '10:00', end: '17:00' },
    },
  },
  {
    id: 'staff-5',
    name: 'Anita Mehta',
    role: 'Nail Technician',
    emoji: '💅',
    specialties: ['Nail Studio', 'Manicure & Pedicure'],
    experience: '5 years',
    available: true,
    schedule: {
      monday: { start: '10:00', end: '20:00' },
      tuesday: { start: '10:00', end: '20:00' },
      wednesday: { start: '10:00', end: '20:00' },
      thursday: { start: '10:00', end: '20:00' },
      friday: null,
      saturday: { start: '09:00', end: '21:00' },
      sunday: { start: '10:00', end: '17:00' },
    },
  },
  {
    id: 'staff-6',
    name: 'Sunita Rao',
    role: 'Massage Therapist',
    emoji: '💆',
    specialties: ['Massages', 'Body Treatments'],
    experience: '9 years',
    available: true,
    schedule: {
      monday: null,
      tuesday: { start: '10:00', end: '20:00' },
      wednesday: { start: '10:00', end: '20:00' },
      thursday: { start: '10:00', end: '20:00' },
      friday: { start: '10:00', end: '20:00' },
      saturday: { start: '09:00', end: '21:00' },
      sunday: { start: '09:00', end: '18:00' },
    },
  },
  {
    id: 'staff-7',
    name: 'Kavita Joshi',
    role: 'Makeup Artist',
    emoji: '💄',
    specialties: ['Make-Up', 'Bridal'],
    experience: '12 years',
    available: true,
    schedule: {
      monday: { start: '09:00', end: '20:00' },
      tuesday: { start: '09:00', end: '20:00' },
      wednesday: null,
      thursday: { start: '09:00', end: '20:00' },
      friday: { start: '09:00', end: '20:00' },
      saturday: { start: '08:00', end: '22:00' },
      sunday: { start: '08:00', end: '20:00' },
    },
  },
  {
    id: 'staff-8',
    name: 'Deepa Singh',
    role: 'Waxing & Skin Specialist',
    emoji: '🌸',
    specialties: ['Waxing', 'Threading', 'Bleach / D-Tan'],
    experience: '6 years',
    available: false,
    schedule: {
      monday: { start: '10:00', end: '19:00' },
      tuesday: { start: '10:00', end: '19:00' },
      wednesday: { start: '10:00', end: '19:00' },
      thursday: null,
      friday: { start: '10:00', end: '19:00' },
      saturday: { start: '10:00', end: '20:00' },
      sunday: null,
    },
  },
];

export const TIME_SLOTS = [
  '9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM',
  '11:00 AM', '11:30 AM', '12:00 PM', '12:30 PM',
  '1:00 PM', '1:30 PM', '2:00 PM', '2:30 PM',
  '3:00 PM', '3:30 PM', '4:00 PM', '4:30 PM',
  '5:00 PM', '5:30 PM', '6:00 PM', '6:30 PM',
  '7:00 PM', '7:30 PM', '8:00 PM',
];

export const DEMO_BUSY_SLOTS: Record<string, string[]> = {
  'staff-1': ['10:00 AM', '10:30 AM', '2:00 PM'],
  'staff-2': ['9:00 AM', '11:00 AM', '3:00 PM', '4:00 PM'],
  'staff-3': ['12:00 PM', '1:00 PM', '5:00 PM'],
  'staff-4': ['10:00 AM', '11:30 AM', '3:30 PM'],
  'staff-5': ['9:30 AM', '2:30 PM', '6:00 PM'],
  'staff-6': ['11:00 AM', '12:00 PM', '4:30 PM', '5:00 PM'],
  'staff-7': ['9:00 AM', '1:30 PM', '7:00 PM'],
  'staff-8': ['10:30 AM', '2:00 PM'],
};
